// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

interface ContactDocumentData {}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ContactDocumentData>, "contact", Lang>;

/**
 * Primary content in *page_home → Slice zone → PhotoGrid → Primary*
 */
export interface HomepageDocumentDataBodyPhotoGridSlicePrimary {
	/**
	 * Section Title field in *page_home → Slice zone → PhotoGrid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].photo_grid.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
}

/**
 * Item content in *page_home → Slice zone → PhotoGrid → Items*
 */
export interface HomepageDocumentDataBodyPhotoGridSliceItem {
	/**
	 * image field in *page_home → Slice zone → PhotoGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].photo_grid.items.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<"grid-1x" | "grid-2x">;
	
	/**
	 * Caption field in *page_home → Slice zone → PhotoGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].photo_grid.items.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * description field in *page_home → Slice zone → PhotoGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[].photo_grid.items.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
}

/**
 * Slice for *page_home → Slice zone*
 */
export type HomepageDocumentDataBodyPhotoGridSlice = prismic.Slice<"photo_grid", Simplify<HomepageDocumentDataBodyPhotoGridSlicePrimary>, Simplify<HomepageDocumentDataBodyPhotoGridSliceItem>>

type HomepageDocumentDataBodySlice = HomepageDocumentDataBodyPhotoGridSlice

/**
 * Content for page_home documents
 */
interface HomepageDocumentData {
	/**
	 * Slice zone field in *page_home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<HomepageDocumentDataBodySlice>;
}

/**
 * page_home document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Content for page_generic documents
 */
interface PageDocumentData {
	/**
	 * title field in *page_generic*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * content field in *page_generic*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * page_generic document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Primary content in *page_portraits → Slice zone → PhotoGrid → Primary*
 */
export interface PagePortraitsDocumentDataBodyPhotoGridSlicePrimary {
	/**
	 * Section Title field in *page_portraits → Slice zone → PhotoGrid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_portraits.body[].photo_grid.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
}

/**
 * Item content in *page_portraits → Slice zone → PhotoGrid → Items*
 */
export interface PagePortraitsDocumentDataBodyPhotoGridSliceItem {
	/**
	 * image field in *page_portraits → Slice zone → PhotoGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_portraits.body[].photo_grid.items.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<"grid-1x" | "grid-2x">;
	
	/**
	 * Caption field in *page_portraits → Slice zone → PhotoGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_portraits.body[].photo_grid.items.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * description field in *page_portraits → Slice zone → PhotoGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_portraits.body[].photo_grid.items.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
}

/**
 * Slice for *page_portraits → Slice zone*
 */
export type PagePortraitsDocumentDataBodyPhotoGridSlice = prismic.Slice<"photo_grid", Simplify<PagePortraitsDocumentDataBodyPhotoGridSlicePrimary>, Simplify<PagePortraitsDocumentDataBodyPhotoGridSliceItem>>

/**
 * Primary content in *page_portraits → Slice zone → RowPortraitGrid → Primary*
 */
export interface PagePortraitsDocumentDataBodyRowportraitgridSlicePrimary {
	/**
	 * Left column Horizontal Alignment field in *page_portraits → Slice zone → RowPortraitGrid → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: left
	 * - **API ID Path**: page_portraits.body[].rowportraitgrid.primary.left_column_horizontal_alignment
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	left_column_horizontal_alignment: prismic.SelectField<"left" | "right", "filled">;
	
	/**
	 * Left Column Vertical Alignment field in *page_portraits → Slice zone → RowPortraitGrid → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: top
	 * - **API ID Path**: page_portraits.body[].rowportraitgrid.primary.left_column_vertical_alignment
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	left_column_vertical_alignment: prismic.SelectField<"top" | "bottom", "filled">;
	
	/**
	 * Left Column Size field in *page_portraits → Slice zone → RowPortraitGrid → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Between 1..12
	 * - **API ID Path**: page_portraits.body[].rowportraitgrid.primary.left_column_size
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	left_column_size: prismic.NumberField;
	
	/**
	 * Left Column Image field in *page_portraits → Slice zone → RowPortraitGrid → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_portraits.body[].rowportraitgrid.primary.left_column_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	left_column_image: prismic.ImageField<"grid">;
	
	/**
	 * Right Column Horizontal Alignment field in *page_portraits → Slice zone → RowPortraitGrid → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: left
	 * - **API ID Path**: page_portraits.body[].rowportraitgrid.primary.right_column_horizontal_alignment
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	right_column_horizontal_alignment: prismic.SelectField<"left" | "right", "filled">;
	
	/**
	 * Right Column Vertical Alignment field in *page_portraits → Slice zone → RowPortraitGrid → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: top
	 * - **API ID Path**: page_portraits.body[].rowportraitgrid.primary.right_column_vertical_alignment
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	right_column_vertical_alignment: prismic.SelectField<"top" | "bottom", "filled">;
	
	/**
	 * Right Column Size field in *page_portraits → Slice zone → RowPortraitGrid → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Between 1..12
	 * - **API ID Path**: page_portraits.body[].rowportraitgrid.primary.right_column_size
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	right_column_size: prismic.NumberField;
	
	/**
	 * Right Column Image field in *page_portraits → Slice zone → RowPortraitGrid → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_portraits.body[].rowportraitgrid.primary.right_column_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	right_column_image: prismic.ImageField<"grid">;
}

/**
 * Slice for *page_portraits → Slice zone*
 */
export type PagePortraitsDocumentDataBodyRowportraitgridSlice = prismic.Slice<"rowportraitgrid", Simplify<PagePortraitsDocumentDataBodyRowportraitgridSlicePrimary>, never>

type PagePortraitsDocumentDataBodySlice = PagePortraitsDocumentDataBodyPhotoGridSlice | PagePortraitsDocumentDataBodyRowportraitgridSlice

/**
 * Content for page_portraits documents
 */
interface PagePortraitsDocumentData {
	/**
	 * Slice zone field in *page_portraits*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_portraits.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<PagePortraitsDocumentDataBodySlice>;
}

/**
 * page_portraits document from Prismic
 *
 * - **API ID**: `page_portraits`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PagePortraitsDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PagePortraitsDocumentData>, "page_portraits", Lang>;

/**
 * Primary content in *Project → Slice zone → PhotoGrid → Primary*
 */
export interface ProjectDocumentDataBodyPhotoGridSlicePrimary {
	/**
	 * Section Title field in *Project → Slice zone → PhotoGrid → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].photo_grid.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;
}

/**
 * Item content in *Project → Slice zone → PhotoGrid → Items*
 */
export interface ProjectDocumentDataBodyPhotoGridSliceItem {
	/**
	 * image field in *Project → Slice zone → PhotoGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].photo_grid.items.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<"grid-1x" | "grid-2x">;
	
	/**
	 * Caption field in *Project → Slice zone → PhotoGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].photo_grid.items.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * description field in *Project → Slice zone → PhotoGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].photo_grid.items.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
}

/**
 * Slice for *Project → Slice zone*
 */
export type ProjectDocumentDataBodyPhotoGridSlice = prismic.Slice<"photo_grid", Simplify<ProjectDocumentDataBodyPhotoGridSlicePrimary>, Simplify<ProjectDocumentDataBodyPhotoGridSliceItem>>

/**
 * Primary content in *Project → Slice zone → Rich Text → Primary*
 */
export interface ProjectDocumentDataBodyRichTextSlicePrimary {
	/**
	 * content field in *Project → Slice zone → Rich Text → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[].rich_text.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Slice for *Project → Slice zone*
 */
export type ProjectDocumentDataBodyRichTextSlice = prismic.Slice<"rich_text", Simplify<ProjectDocumentDataBodyRichTextSlicePrimary>, never>

type ProjectDocumentDataBodySlice = ProjectDocumentDataBodyPhotoGridSlice | ProjectDocumentDataBodyRichTextSlice

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
	/**
	 * title field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * thumbnail field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.thumbnail
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	thumbnail: prismic.ImageField<"retina">;
	
	/**
	 * Slice zone field in *Project*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<ProjectDocumentDataBodySlice>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;

/**
 * Item in *page_projects → projects*
 */
export interface ProjectsPageDocumentDataProjectsItem {
	/**
	 * project field in *page_projects → projects*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_page.projects[].project
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	project: prismic.ContentRelationshipField<"project">;
}

/**
 * Content for page_projects documents
 */
interface ProjectsPageDocumentData {
	/**
	 * title field in *page_projects*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * projects field in *page_projects*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects_page.projects[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	projects: prismic.GroupField<Simplify<ProjectsPageDocumentDataProjectsItem>>;
}

/**
 * page_projects document from Prismic
 *
 * - **API ID**: `projects_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ProjectsPageDocumentData>, "projects_page", Lang>;

export type AllDocumentTypes = ContactDocument | HomepageDocument | PageDocument | PagePortraitsDocument | ProjectDocument | ProjectsPageDocument;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			ContactDocument,
			ContactDocumentData,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataBodyPhotoGridSlicePrimary,
			HomepageDocumentDataBodyPhotoGridSliceItem,
			HomepageDocumentDataBodySlice,
			PageDocument,
			PageDocumentData,
			PagePortraitsDocument,
			PagePortraitsDocumentData,
			PagePortraitsDocumentDataBodyPhotoGridSlicePrimary,
			PagePortraitsDocumentDataBodyPhotoGridSliceItem,
			PagePortraitsDocumentDataBodyRowportraitgridSlicePrimary,
			PagePortraitsDocumentDataBodySlice,
			ProjectDocument,
			ProjectDocumentData,
			ProjectDocumentDataBodyPhotoGridSlicePrimary,
			ProjectDocumentDataBodyPhotoGridSliceItem,
			ProjectDocumentDataBodyRichTextSlicePrimary,
			ProjectDocumentDataBodySlice,
			ProjectsPageDocument,
			ProjectsPageDocumentData,
			ProjectsPageDocumentDataProjectsItem,
			AllDocumentTypes
		}
	}
}